# Generated by Django 5.1.6 on 2025-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ManyToManyField(related_name='notificaciones', to='usuarios.perfilusuario', verbose_name='Destinatario:'),
        ),
    ]
