# Generated by Django 5.1.6 on 2025-03-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_remove_notificacion_destinatario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='destinatario',
            new_name='destinatarios',
        ),
    ]
