# Generated by Django 5.1.6 on 2025-03-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_rename_destinatario_notificacion_destinatarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la nueva publicacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=150, verbose_name='Mensaje de la notificacion:'),
        ),
    ]
