# Generated by Django 5.1.6 on 2025-03-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_notificacion_url_alter_notificacion_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
