# Generated by Django 5.1.6 on 2025-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_notificacion_options'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=150, verbose_name='Mensaje de la notificacion:')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leida?:')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL de la nueva publicacion')),
                ('destinatarios', models.ManyToManyField(related_name='notificaciones_publicaciones', to='usuarios.perfilusuario', verbose_name='Destinatarios:')),
            ],
            options={
                'verbose_name': 'Notificacion publicacion',
                'verbose_name_plural': 'Notificacion publicaciones',
            },
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
