# Generated by Django 5.1.6 on 2025-03-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_notificacionpublicacion_delete_notificacion'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionResponderComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=150, verbose_name='Mensaje de la notificacion:')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leida?')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_comentarios', to='usuarios.perfilusuario', verbose_name='Destinatario:')),
            ],
        ),
    ]
