# Generated by Django 5.1.6 on 2025-03-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0007_notificacionrespondercomentario'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificacionResponderComentario',
            new_name='NotificacionComentario',
        ),
        migrations.AlterModelOptions(
            name='notificacioncomentario',
            options={'verbose_name': 'Notificacion comentario', 'verbose_name_plural': 'Notificacion comentarios'},
        ),
    ]
