# Generated by Django 5.1.6 on 2025-03-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0008_rename_notificacionrespondercomentario_notificacioncomentario_and_more'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionSeguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=50, verbose_name='Le han empezado a seguir')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_destinatario', to='usuarios.perfilusuario', verbose_name='Usuario seguido:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_usuario', to='usuarios.perfilusuario', verbose_name='Usuario:')),
            ],
        ),
    ]
