# Generated by Django 5.1.6 on 2025-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0009_notificacionseguir'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionseguir',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='¿Leida?'),
        ),
    ]
