# Generated by Django 5.1.6 on 2025-03-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0010_notificacionseguir_leida'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioncomentario',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_comentario', to='usuarios.perfilusuario', verbose_name='Autor:'),
            preserve_default=False,
        ),
    ]
