# Generated by Django 5.1.6 on 2025-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0011_notificacioncomentario_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionseguir',
            name='mensaje',
            field=models.CharField(max_length=150, verbose_name='Le han empezado a seguir'),
        ),
    ]
