# Generated by Django 5.1.6 on 2025-03-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0012_alter_notificacionseguir_mensaje'),
        ('publicaciones', '0012_respuestacomentario_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioncomentario',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion', verbose_name='Publicacion:'),
            preserve_default=False,
        ),
    ]
