# Generated by Django 5.1.6 on 2025-03-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0013_notificacioncomentario_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncomentario',
            name='mensaje',
            field=models.CharField(max_length=350, verbose_name='Mensaje de la notificacion:'),
        ),
    ]
