# Generated by Django 5.1.6 on 2025-03-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0014_alter_notificacioncomentario_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioncomentario',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de la publicacion comentada:'),
        ),
    ]
