# Generated by Django 5.1.6 on 2025-03-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0015_notificacioncomentario_url'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionseguir',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url del perfil que empieza a seguir:'),
        ),
        migrations.AlterField(
            model_name='notificacionseguir',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_destinatario', to='usuarios.perfilusuario', verbose_name='Usuario que ha empezado a seguir:'),
        ),
    ]
