# Generated by Django 5.1.6 on 2025-03-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0016_notificacionseguir_url_and_more'),
        ('publicaciones', '0012_respuestacomentario_publicacion'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionRespuestaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leida?')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url de la publicacion:')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.comentario', verbose_name='Comentario contestado:')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_destinatario', to='usuarios.perfilusuario', verbose_name='Autor del comentario:')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion', verbose_name='Publicacion que pertenece la respuesta:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_usuario', to='usuarios.perfilusuario', verbose_name='Autor que ha contestado:')),
            ],
        ),
    ]
