# Generated by Django 5.1.6 on 2025-03-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0018_notificacionmegusta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionseguir',
            name='mensaje',
        ),
    ]
