# Generated by Django 5.1.6 on 2025-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0019_remove_notificacionseguir_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacioncomentario',
            name='mensaje',
        ),
    ]
