# Generated by Django 5.1.6 on 2025-03-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0020_remove_notificacioncomentario_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacioncomentario',
            options={'verbose_name': 'Notificacion comentario', 'verbose_name_plural': 'Notificaciones de comentarios'},
        ),
        migrations.AlterModelOptions(
            name='notificacionmegusta',
            options={'verbose_name': 'Notificacion de me gusta', 'verbose_name_plural': 'Notificaciones de me gusta'},
        ),
        migrations.AlterModelOptions(
            name='notificacionpublicacion',
            options={'verbose_name': 'Notificacion publicacion', 'verbose_name_plural': 'Notificaciones de publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='notificacionrespuestacomentario',
            options={'verbose_name': 'Notificacion de respuesta a comentario', 'verbose_name_plural': 'Notificaciones de respuestas a comentarios'},
        ),
        migrations.AlterModelOptions(
            name='notificacionseguir',
            options={'verbose_name': 'Notificacion seguir', 'verbose_name_plural': 'Notificaciones de seguir'},
        ),
    ]
