# Generated by Django 5.1.6 on 2025-03-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0021_alter_notificacioncomentario_options_and_more'),
        ('publicaciones', '0012_respuestacomentario_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioncomentario',
            name='comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.comentario', verbose_name='Comentario:'),
            preserve_default=False,
        ),
    ]
