# Generated by Django 5.1.6 on 2025-03-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0022_notificacioncomentario_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacioncomentario',
            name='comentario',
        ),
    ]
