# Generated by Django 5.1.6 on 2025-03-25 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0023_remove_notificacioncomentario_comentario'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionpublicacion',
            name='destinatarios',
        ),
        migrations.AddField(
            model_name='notificacionpublicacion',
            name='destinatario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_publicaciones', to='usuarios.perfilusuario', verbose_name='Destinatario:'),
            preserve_default=False,
        ),
    ]
