# Generated by Django 5.1.6 on 2025-03-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0024_remove_notificacionpublicacion_destinatarios_and_more'),
        ('publicaciones', '0012_respuestacomentario_publicacion'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionpublicacion',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notificacionpublicacion',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_publicacion', to='usuarios.perfilusuario', verbose_name='Autor:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacionpublicacion',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion', verbose_name='Publicacion:'),
            preserve_default=False,
        ),
    ]
