# Generated by Django 5.1.6 on 2025-03-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_conversacion_options_alter_mensaje_options_and_more'),
        ('notificaciones', '0025_remove_notificacionpublicacion_mensaje_and_more'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False, verbose_name='¿Leida?')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL de la conversacion')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.conversacion', verbose_name='Conversacion que pertenece el mensaje:')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_destinatario', to='usuarios.perfilusuario', verbose_name='Usuario que recibe el mensaje:')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.mensaje', verbose_name='Mensaje:')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_usuarios', to='usuarios.perfilusuario', verbose_name='Usuario que envia el mensaje:')),
            ],
            options={
                'verbose_name': 'Notificacion de mensaje',
                'verbose_name_plural': 'Notificaciones de mensajes',
            },
        ),
    ]
