# Generated by Django 5.1.6 on 2025-04-12 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0026_notificacionmensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionmegusta',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
    ]
