# Generated by Django 5.1.6 on 2025-04-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0027_notificacionmegusta_fecha_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionmegusta',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
    ]
