# Generated by Django 5.1.6 on 2025-04-12 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0028_alter_notificacionmegusta_fecha_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioncomentario',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
        migrations.AddField(
            model_name='notificacionmensaje',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
        migrations.AddField(
            model_name='notificacionpublicacion',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
        migrations.AddField(
            model_name='notificacionrespuestacomentario',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
        migrations.AddField(
            model_name='notificacionseguir',
            name='fecha_notificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha notificacion:'),
        ),
    ]
