# Generated by Django 5.1.6 on 2025-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0029_notificacioncomentario_fecha_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncomentario',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
        migrations.AlterField(
            model_name='notificacionmensaje',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
        migrations.AlterField(
            model_name='notificacionpublicacion',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
        migrations.AlterField(
            model_name='notificacionrespuestacomentario',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
        migrations.AlterField(
            model_name='notificacionseguir',
            name='fecha_notificacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha notificacion:'),
        ),
    ]
