# Generated by Django 5.1.6 on 2025-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='biografia',
            field=models.TextField(blank=True, max_length=300, verbose_name='Biografia del ususario:'),
        ),
    ]
