# Generated by Django 5.1.6 on 2025-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
    ]
