# Generated by Django 5.1.6 on 2025-03-04 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Titulo de la publicacion:')),
                ('imagen', models.ImageField(upload_to='publicaciones/img/', verbose_name='Imagen del post:')),
                ('video', models.FileField(null=True, upload_to='publicaciones/video/', verbose_name='Video de la publicacion:')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion:')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='usuarios.perfilusuario', verbose_name='Autor:')),
                ('likes', models.ManyToManyField(related_name='likes_publicacion', to='usuarios.perfilusuario', verbose_name='Likes de la publicacion:')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=500, verbose_name='Comentario de la publicacion:')),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del comentario:')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.perfilusuario', verbose_name='Autor:')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicacion', verbose_name='Publicacion a comentar:')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
