# Generated by Django 5.1.6 on 2025-03-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(blank=True, max_length=300, verbose_name='Contenido de la publicacion'),
        ),
    ]
