# Generated by Django 5.1.6 on 2025-03-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_comentario_autor_alter_publicacion_autor_and_more'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.perfilusuario', verbose_name='Autor:'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='usuarios.perfilusuario', verbose_name='Autor:'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.ManyToManyField(related_name='likes_publicacion', to='usuarios.perfilusuario', verbose_name='Likes de la publicacion:'),
        ),
    ]
