# Generated by Django 5.1.6 on 2025-03-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_comentario_autor_alter_publicacion_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='contenido',
        ),
        migrations.AddField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default=1, max_length=500, verbose_name='Comentario de la publicacion:'),
            preserve_default=False,
        ),
    ]
