# Generated by Django 5.1.6 on 2025-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_remove_comentario_contenido_comentario_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=500, verbose_name='Nuevo comentario:'),
        ),
    ]
