# Generated by Django 5.1.6 on 2025-03-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_comentario_padre'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='padre',
        ),
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Contenido de la respuesta:')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta:')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuarios.perfilusuario', verbose_name='Autor:')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='publicaciones.comentario', verbose_name='Comentario a responder:')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
