# Generated by Django 5.1.6 on 2025-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_remove_comentario_padre_respuestacomentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuestacomentario',
            old_name='texto',
            new_name='respuesta',
        ),
    ]
