# Generated by Django 5.1.6 on 2025-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_rename_texto_respuestacomentario_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacomentario',
            name='respuesta',
            field=models.TextField(max_length=300, verbose_name='Contenido de la respuesta:'),
        ),
    ]
