# Generated by Django 5.1.6 on 2025-03-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0010_alter_respuestacomentario_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacomentario',
            name='respuesta',
            field=models.TextField(max_length=300, verbose_name='Responder comentario:'),
        ),
    ]
