# Generated by Django 5.1.6 on 2025-03-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_alter_respuestacomentario_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestacomentario',
            name='publicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_publicacion', to='publicaciones.publicacion', verbose_name='Publicacion:'),
            preserve_default=False,
        ),
    ]
