# Generated by Django 5.1.6 on 2025-04-07 16:33

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0012_respuestacomentario_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=thumbnails.fields.ImageField(upload_to='publicaciones/img/', verbose_name='Imagen del post:'),
        ),
    ]
