# Generated by Django 5.2 on 2025-05-01 16:03

import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='publicaciones/img/', verbose_name='Imagen del post:'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo de la publicacion:'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/video/', verbose_name='Video de la publicacion:'),
        ),
    ]
