# Generated by Django 5.1.6 on 2025-03-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio de la conversacion:')),
                ('usuario1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_user1', to='usuarios.perfilusuario', verbose_name='Usuario1:')),
                ('usuario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_user2', to='usuarios.perfilusuario', verbose_name='Usuario1:')),
            ],
            options={
                'unique_together': {('usuario1', 'usuario2')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150, verbose_name='Contenido del mensaje:')),
                ('fecha_mensaje', models.DateTimeField(verbose_name='Fecha del mensaje:')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Leido?')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_mensaje', to='usuarios.perfilusuario', verbose_name='Usuario que envia el mensaje:')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='mensajes.conversacion', verbose_name='Conversacion a la que pertenece:')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_mensaje', to='usuarios.perfilusuario', verbose_name='Usuario que recibe el mensaje')),
            ],
        ),
    ]
