# Generated by Django 5.1.6 on 2025-03-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        ('usuarios', '0003_alter_follow_fecha_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacion',
            options={'verbose_name': 'Conversacion', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_user2', to='usuarios.perfilusuario', verbose_name='Usuario2:'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_mensaje',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del mensaje:'),
        ),
    ]
